services:
    nginx:
      container_name: nginx-front-ingress
      image: nginx:alpine
      restart: always
      network_mode: "host"
      volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "/var/www/html/:/var/www/html/"

